# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSExample
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Alamofire', '~> 5.0.0-beta.2'

  target 'iOSExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSExampleUITests' do
    # Pods for testing
  end

end
