// This file is generated by rust-protobuf 2.8.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `core/Discover.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_0;

#[derive(PartialEq,Clone,Default)]
pub struct Endpoint {
    // message fields
    pub address: ::std::vec::Vec<u8>,
    pub port: i32,
    pub nodeId: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Endpoint {
    fn default() -> &'a Endpoint {
        <Endpoint as ::protobuf::Message>::default_instance()
    }
}

impl Endpoint {
    pub fn new() -> Endpoint {
        ::std::default::Default::default()
    }

    // bytes address = 1;


    pub fn get_address(&self) -> &[u8] {
        &self.address
    }
    pub fn clear_address(&mut self) {
        self.address.clear();
    }

    // Param is passed by value, moved
    pub fn set_address(&mut self, v: ::std::vec::Vec<u8>) {
        self.address = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_address(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.address
    }

    // Take field
    pub fn take_address(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.address, ::std::vec::Vec::new())
    }

    // int32 port = 2;


    pub fn get_port(&self) -> i32 {
        self.port
    }
    pub fn clear_port(&mut self) {
        self.port = 0;
    }

    // Param is passed by value, moved
    pub fn set_port(&mut self, v: i32) {
        self.port = v;
    }

    // bytes nodeId = 3;


    pub fn get_nodeId(&self) -> &[u8] {
        &self.nodeId
    }
    pub fn clear_nodeId(&mut self) {
        self.nodeId.clear();
    }

    // Param is passed by value, moved
    pub fn set_nodeId(&mut self, v: ::std::vec::Vec<u8>) {
        self.nodeId = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_nodeId(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.nodeId
    }

    // Take field
    pub fn take_nodeId(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.nodeId, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for Endpoint {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.address)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.port = tmp;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.nodeId)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.address.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.address);
        }
        if self.port != 0 {
            my_size += ::protobuf::rt::value_size(2, self.port, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.nodeId.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.nodeId);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.address.is_empty() {
            os.write_bytes(1, &self.address)?;
        }
        if self.port != 0 {
            os.write_int32(2, self.port)?;
        }
        if !self.nodeId.is_empty() {
            os.write_bytes(3, &self.nodeId)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Endpoint {
        Endpoint::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "address",
                    |m: &Endpoint| { &m.address },
                    |m: &mut Endpoint| { &mut m.address },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "port",
                    |m: &Endpoint| { &m.port },
                    |m: &mut Endpoint| { &mut m.port },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "nodeId",
                    |m: &Endpoint| { &m.nodeId },
                    |m: &mut Endpoint| { &mut m.nodeId },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Endpoint>(
                    "Endpoint",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Endpoint {
        static mut instance: ::protobuf::lazy::Lazy<Endpoint> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Endpoint,
        };
        unsafe {
            instance.get(Endpoint::new)
        }
    }
}

impl ::protobuf::Clear for Endpoint {
    fn clear(&mut self) {
        self.address.clear();
        self.port = 0;
        self.nodeId.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Endpoint {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Endpoint {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct PingMessage {
    // message fields
    pub from: ::protobuf::SingularPtrField<Endpoint>,
    pub to: ::protobuf::SingularPtrField<Endpoint>,
    pub version: i32,
    pub timestamp: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a PingMessage {
    fn default() -> &'a PingMessage {
        <PingMessage as ::protobuf::Message>::default_instance()
    }
}

impl PingMessage {
    pub fn new() -> PingMessage {
        ::std::default::Default::default()
    }

    // .protocol.Endpoint from = 1;


    pub fn get_from(&self) -> &Endpoint {
        self.from.as_ref().unwrap_or_else(|| Endpoint::default_instance())
    }
    pub fn clear_from(&mut self) {
        self.from.clear();
    }

    pub fn has_from(&self) -> bool {
        self.from.is_some()
    }

    // Param is passed by value, moved
    pub fn set_from(&mut self, v: Endpoint) {
        self.from = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_from(&mut self) -> &mut Endpoint {
        if self.from.is_none() {
            self.from.set_default();
        }
        self.from.as_mut().unwrap()
    }

    // Take field
    pub fn take_from(&mut self) -> Endpoint {
        self.from.take().unwrap_or_else(|| Endpoint::new())
    }

    // .protocol.Endpoint to = 2;


    pub fn get_to(&self) -> &Endpoint {
        self.to.as_ref().unwrap_or_else(|| Endpoint::default_instance())
    }
    pub fn clear_to(&mut self) {
        self.to.clear();
    }

    pub fn has_to(&self) -> bool {
        self.to.is_some()
    }

    // Param is passed by value, moved
    pub fn set_to(&mut self, v: Endpoint) {
        self.to = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_to(&mut self) -> &mut Endpoint {
        if self.to.is_none() {
            self.to.set_default();
        }
        self.to.as_mut().unwrap()
    }

    // Take field
    pub fn take_to(&mut self) -> Endpoint {
        self.to.take().unwrap_or_else(|| Endpoint::new())
    }

    // int32 version = 3;


    pub fn get_version(&self) -> i32 {
        self.version
    }
    pub fn clear_version(&mut self) {
        self.version = 0;
    }

    // Param is passed by value, moved
    pub fn set_version(&mut self, v: i32) {
        self.version = v;
    }

    // int64 timestamp = 4;


    pub fn get_timestamp(&self) -> i64 {
        self.timestamp
    }
    pub fn clear_timestamp(&mut self) {
        self.timestamp = 0;
    }

    // Param is passed by value, moved
    pub fn set_timestamp(&mut self, v: i64) {
        self.timestamp = v;
    }
}

impl ::protobuf::Message for PingMessage {
    fn is_initialized(&self) -> bool {
        for v in &self.from {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.to {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.from)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.to)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.version = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.timestamp = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.from.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.to.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.version != 0 {
            my_size += ::protobuf::rt::value_size(3, self.version, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.timestamp != 0 {
            my_size += ::protobuf::rt::value_size(4, self.timestamp, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.from.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.to.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.version != 0 {
            os.write_int32(3, self.version)?;
        }
        if self.timestamp != 0 {
            os.write_int64(4, self.timestamp)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> PingMessage {
        PingMessage::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Endpoint>>(
                    "from",
                    |m: &PingMessage| { &m.from },
                    |m: &mut PingMessage| { &mut m.from },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Endpoint>>(
                    "to",
                    |m: &PingMessage| { &m.to },
                    |m: &mut PingMessage| { &mut m.to },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "version",
                    |m: &PingMessage| { &m.version },
                    |m: &mut PingMessage| { &mut m.version },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "timestamp",
                    |m: &PingMessage| { &m.timestamp },
                    |m: &mut PingMessage| { &mut m.timestamp },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<PingMessage>(
                    "PingMessage",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static PingMessage {
        static mut instance: ::protobuf::lazy::Lazy<PingMessage> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const PingMessage,
        };
        unsafe {
            instance.get(PingMessage::new)
        }
    }
}

impl ::protobuf::Clear for PingMessage {
    fn clear(&mut self) {
        self.from.clear();
        self.to.clear();
        self.version = 0;
        self.timestamp = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for PingMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PingMessage {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct PongMessage {
    // message fields
    pub from: ::protobuf::SingularPtrField<Endpoint>,
    pub echo: i32,
    pub timestamp: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a PongMessage {
    fn default() -> &'a PongMessage {
        <PongMessage as ::protobuf::Message>::default_instance()
    }
}

impl PongMessage {
    pub fn new() -> PongMessage {
        ::std::default::Default::default()
    }

    // .protocol.Endpoint from = 1;


    pub fn get_from(&self) -> &Endpoint {
        self.from.as_ref().unwrap_or_else(|| Endpoint::default_instance())
    }
    pub fn clear_from(&mut self) {
        self.from.clear();
    }

    pub fn has_from(&self) -> bool {
        self.from.is_some()
    }

    // Param is passed by value, moved
    pub fn set_from(&mut self, v: Endpoint) {
        self.from = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_from(&mut self) -> &mut Endpoint {
        if self.from.is_none() {
            self.from.set_default();
        }
        self.from.as_mut().unwrap()
    }

    // Take field
    pub fn take_from(&mut self) -> Endpoint {
        self.from.take().unwrap_or_else(|| Endpoint::new())
    }

    // int32 echo = 2;


    pub fn get_echo(&self) -> i32 {
        self.echo
    }
    pub fn clear_echo(&mut self) {
        self.echo = 0;
    }

    // Param is passed by value, moved
    pub fn set_echo(&mut self, v: i32) {
        self.echo = v;
    }

    // int64 timestamp = 3;


    pub fn get_timestamp(&self) -> i64 {
        self.timestamp
    }
    pub fn clear_timestamp(&mut self) {
        self.timestamp = 0;
    }

    // Param is passed by value, moved
    pub fn set_timestamp(&mut self, v: i64) {
        self.timestamp = v;
    }
}

impl ::protobuf::Message for PongMessage {
    fn is_initialized(&self) -> bool {
        for v in &self.from {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.from)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.echo = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.timestamp = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.from.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.echo != 0 {
            my_size += ::protobuf::rt::value_size(2, self.echo, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.timestamp != 0 {
            my_size += ::protobuf::rt::value_size(3, self.timestamp, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.from.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.echo != 0 {
            os.write_int32(2, self.echo)?;
        }
        if self.timestamp != 0 {
            os.write_int64(3, self.timestamp)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> PongMessage {
        PongMessage::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Endpoint>>(
                    "from",
                    |m: &PongMessage| { &m.from },
                    |m: &mut PongMessage| { &mut m.from },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "echo",
                    |m: &PongMessage| { &m.echo },
                    |m: &mut PongMessage| { &mut m.echo },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "timestamp",
                    |m: &PongMessage| { &m.timestamp },
                    |m: &mut PongMessage| { &mut m.timestamp },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<PongMessage>(
                    "PongMessage",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static PongMessage {
        static mut instance: ::protobuf::lazy::Lazy<PongMessage> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const PongMessage,
        };
        unsafe {
            instance.get(PongMessage::new)
        }
    }
}

impl ::protobuf::Clear for PongMessage {
    fn clear(&mut self) {
        self.from.clear();
        self.echo = 0;
        self.timestamp = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for PongMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PongMessage {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct FindNeighbours {
    // message fields
    pub from: ::protobuf::SingularPtrField<Endpoint>,
    pub targetId: ::std::vec::Vec<u8>,
    pub timestamp: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a FindNeighbours {
    fn default() -> &'a FindNeighbours {
        <FindNeighbours as ::protobuf::Message>::default_instance()
    }
}

impl FindNeighbours {
    pub fn new() -> FindNeighbours {
        ::std::default::Default::default()
    }

    // .protocol.Endpoint from = 1;


    pub fn get_from(&self) -> &Endpoint {
        self.from.as_ref().unwrap_or_else(|| Endpoint::default_instance())
    }
    pub fn clear_from(&mut self) {
        self.from.clear();
    }

    pub fn has_from(&self) -> bool {
        self.from.is_some()
    }

    // Param is passed by value, moved
    pub fn set_from(&mut self, v: Endpoint) {
        self.from = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_from(&mut self) -> &mut Endpoint {
        if self.from.is_none() {
            self.from.set_default();
        }
        self.from.as_mut().unwrap()
    }

    // Take field
    pub fn take_from(&mut self) -> Endpoint {
        self.from.take().unwrap_or_else(|| Endpoint::new())
    }

    // bytes targetId = 2;


    pub fn get_targetId(&self) -> &[u8] {
        &self.targetId
    }
    pub fn clear_targetId(&mut self) {
        self.targetId.clear();
    }

    // Param is passed by value, moved
    pub fn set_targetId(&mut self, v: ::std::vec::Vec<u8>) {
        self.targetId = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_targetId(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.targetId
    }

    // Take field
    pub fn take_targetId(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.targetId, ::std::vec::Vec::new())
    }

    // int64 timestamp = 3;


    pub fn get_timestamp(&self) -> i64 {
        self.timestamp
    }
    pub fn clear_timestamp(&mut self) {
        self.timestamp = 0;
    }

    // Param is passed by value, moved
    pub fn set_timestamp(&mut self, v: i64) {
        self.timestamp = v;
    }
}

impl ::protobuf::Message for FindNeighbours {
    fn is_initialized(&self) -> bool {
        for v in &self.from {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.from)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.targetId)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.timestamp = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.from.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if !self.targetId.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.targetId);
        }
        if self.timestamp != 0 {
            my_size += ::protobuf::rt::value_size(3, self.timestamp, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.from.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if !self.targetId.is_empty() {
            os.write_bytes(2, &self.targetId)?;
        }
        if self.timestamp != 0 {
            os.write_int64(3, self.timestamp)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> FindNeighbours {
        FindNeighbours::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Endpoint>>(
                    "from",
                    |m: &FindNeighbours| { &m.from },
                    |m: &mut FindNeighbours| { &mut m.from },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "targetId",
                    |m: &FindNeighbours| { &m.targetId },
                    |m: &mut FindNeighbours| { &mut m.targetId },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "timestamp",
                    |m: &FindNeighbours| { &m.timestamp },
                    |m: &mut FindNeighbours| { &mut m.timestamp },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<FindNeighbours>(
                    "FindNeighbours",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static FindNeighbours {
        static mut instance: ::protobuf::lazy::Lazy<FindNeighbours> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const FindNeighbours,
        };
        unsafe {
            instance.get(FindNeighbours::new)
        }
    }
}

impl ::protobuf::Clear for FindNeighbours {
    fn clear(&mut self) {
        self.from.clear();
        self.targetId.clear();
        self.timestamp = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for FindNeighbours {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FindNeighbours {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Neighbours {
    // message fields
    pub from: ::protobuf::SingularPtrField<Endpoint>,
    pub neighbours: ::protobuf::RepeatedField<Endpoint>,
    pub timestamp: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Neighbours {
    fn default() -> &'a Neighbours {
        <Neighbours as ::protobuf::Message>::default_instance()
    }
}

impl Neighbours {
    pub fn new() -> Neighbours {
        ::std::default::Default::default()
    }

    // .protocol.Endpoint from = 1;


    pub fn get_from(&self) -> &Endpoint {
        self.from.as_ref().unwrap_or_else(|| Endpoint::default_instance())
    }
    pub fn clear_from(&mut self) {
        self.from.clear();
    }

    pub fn has_from(&self) -> bool {
        self.from.is_some()
    }

    // Param is passed by value, moved
    pub fn set_from(&mut self, v: Endpoint) {
        self.from = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_from(&mut self) -> &mut Endpoint {
        if self.from.is_none() {
            self.from.set_default();
        }
        self.from.as_mut().unwrap()
    }

    // Take field
    pub fn take_from(&mut self) -> Endpoint {
        self.from.take().unwrap_or_else(|| Endpoint::new())
    }

    // repeated .protocol.Endpoint neighbours = 2;


    pub fn get_neighbours(&self) -> &[Endpoint] {
        &self.neighbours
    }
    pub fn clear_neighbours(&mut self) {
        self.neighbours.clear();
    }

    // Param is passed by value, moved
    pub fn set_neighbours(&mut self, v: ::protobuf::RepeatedField<Endpoint>) {
        self.neighbours = v;
    }

    // Mutable pointer to the field.
    pub fn mut_neighbours(&mut self) -> &mut ::protobuf::RepeatedField<Endpoint> {
        &mut self.neighbours
    }

    // Take field
    pub fn take_neighbours(&mut self) -> ::protobuf::RepeatedField<Endpoint> {
        ::std::mem::replace(&mut self.neighbours, ::protobuf::RepeatedField::new())
    }

    // int64 timestamp = 3;


    pub fn get_timestamp(&self) -> i64 {
        self.timestamp
    }
    pub fn clear_timestamp(&mut self) {
        self.timestamp = 0;
    }

    // Param is passed by value, moved
    pub fn set_timestamp(&mut self, v: i64) {
        self.timestamp = v;
    }
}

impl ::protobuf::Message for Neighbours {
    fn is_initialized(&self) -> bool {
        for v in &self.from {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.neighbours {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.from)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.neighbours)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.timestamp = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.from.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        for value in &self.neighbours {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if self.timestamp != 0 {
            my_size += ::protobuf::rt::value_size(3, self.timestamp, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.from.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        for v in &self.neighbours {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if self.timestamp != 0 {
            os.write_int64(3, self.timestamp)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Neighbours {
        Neighbours::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Endpoint>>(
                    "from",
                    |m: &Neighbours| { &m.from },
                    |m: &mut Neighbours| { &mut m.from },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Endpoint>>(
                    "neighbours",
                    |m: &Neighbours| { &m.neighbours },
                    |m: &mut Neighbours| { &mut m.neighbours },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "timestamp",
                    |m: &Neighbours| { &m.timestamp },
                    |m: &mut Neighbours| { &mut m.timestamp },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Neighbours>(
                    "Neighbours",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Neighbours {
        static mut instance: ::protobuf::lazy::Lazy<Neighbours> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Neighbours,
        };
        unsafe {
            instance.get(Neighbours::new)
        }
    }
}

impl ::protobuf::Clear for Neighbours {
    fn clear(&mut self) {
        self.from.clear();
        self.neighbours.clear();
        self.timestamp = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Neighbours {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Neighbours {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct BackupMessage {
    // message fields
    pub flag: bool,
    pub priority: i32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a BackupMessage {
    fn default() -> &'a BackupMessage {
        <BackupMessage as ::protobuf::Message>::default_instance()
    }
}

impl BackupMessage {
    pub fn new() -> BackupMessage {
        ::std::default::Default::default()
    }

    // bool flag = 1;


    pub fn get_flag(&self) -> bool {
        self.flag
    }
    pub fn clear_flag(&mut self) {
        self.flag = false;
    }

    // Param is passed by value, moved
    pub fn set_flag(&mut self, v: bool) {
        self.flag = v;
    }

    // int32 priority = 2;


    pub fn get_priority(&self) -> i32 {
        self.priority
    }
    pub fn clear_priority(&mut self) {
        self.priority = 0;
    }

    // Param is passed by value, moved
    pub fn set_priority(&mut self, v: i32) {
        self.priority = v;
    }
}

impl ::protobuf::Message for BackupMessage {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.flag = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.priority = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.flag != false {
            my_size += 2;
        }
        if self.priority != 0 {
            my_size += ::protobuf::rt::value_size(2, self.priority, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.flag != false {
            os.write_bool(1, self.flag)?;
        }
        if self.priority != 0 {
            os.write_int32(2, self.priority)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> BackupMessage {
        BackupMessage::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                    "flag",
                    |m: &BackupMessage| { &m.flag },
                    |m: &mut BackupMessage| { &mut m.flag },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "priority",
                    |m: &BackupMessage| { &m.priority },
                    |m: &mut BackupMessage| { &mut m.priority },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<BackupMessage>(
                    "BackupMessage",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static BackupMessage {
        static mut instance: ::protobuf::lazy::Lazy<BackupMessage> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const BackupMessage,
        };
        unsafe {
            instance.get(BackupMessage::new)
        }
    }
}

impl ::protobuf::Clear for BackupMessage {
    fn clear(&mut self) {
        self.flag = false;
        self.priority = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for BackupMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BackupMessage {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x13core/Discover.proto\x12\x08protocol\"P\n\x08Endpoint\x12\x18\n\x07\
    address\x18\x01\x20\x01(\x0cR\x07address\x12\x12\n\x04port\x18\x02\x20\
    \x01(\x05R\x04port\x12\x16\n\x06nodeId\x18\x03\x20\x01(\x0cR\x06nodeId\"\
    \x91\x01\n\x0bPingMessage\x12&\n\x04from\x18\x01\x20\x01(\x0b2\x12.proto\
    col.EndpointR\x04from\x12\"\n\x02to\x18\x02\x20\x01(\x0b2\x12.protocol.E\
    ndpointR\x02to\x12\x18\n\x07version\x18\x03\x20\x01(\x05R\x07version\x12\
    \x1c\n\ttimestamp\x18\x04\x20\x01(\x03R\ttimestamp\"g\n\x0bPongMessage\
    \x12&\n\x04from\x18\x01\x20\x01(\x0b2\x12.protocol.EndpointR\x04from\x12\
    \x12\n\x04echo\x18\x02\x20\x01(\x05R\x04echo\x12\x1c\n\ttimestamp\x18\
    \x03\x20\x01(\x03R\ttimestamp\"r\n\x0eFindNeighbours\x12&\n\x04from\x18\
    \x01\x20\x01(\x0b2\x12.protocol.EndpointR\x04from\x12\x1a\n\x08targetId\
    \x18\x02\x20\x01(\x0cR\x08targetId\x12\x1c\n\ttimestamp\x18\x03\x20\x01(\
    \x03R\ttimestamp\"\x86\x01\n\nNeighbours\x12&\n\x04from\x18\x01\x20\x01(\
    \x0b2\x12.protocol.EndpointR\x04from\x122\n\nneighbours\x18\x02\x20\x03(\
    \x0b2\x12.protocol.EndpointR\nneighbours\x12\x1c\n\ttimestamp\x18\x03\
    \x20\x01(\x03R\ttimestamp\"?\n\rBackupMessage\x12\x12\n\x04flag\x18\x01\
    \x20\x01(\x08R\x04flag\x12\x1a\n\x08priority\x18\x02\x20\x01(\x05R\x08pr\
    iorityBF\n\x0forg.tron.protosB\x08DiscoverZ)github.com/tronprotocol/grpc\
    -gateway/coreJ\xc9\x0c\n\x06\x12\x04\0\0+\x01\n\x08\n\x01\x0c\x12\x03\0\
    \0\x12\n\x08\n\x01\x02\x12\x03\x02\x08\x10\n\x08\n\x01\x08\x12\x03\x05\0\
    (\nH\n\x02\x08\x01\x12\x03\x05\0(\"=Specify\x20the\x20name\x20of\x20the\
    \x20package\x20that\x20generated\x20the\x20Java\x20file\n\n\x08\n\x01\
    \x08\x12\x03\x06\0)\n=\n\x02\x08\x08\x12\x03\x06\0)\"2Specify\x20the\x20\
    class\x20name\x20of\x20the\x20generated\x20Java\x20file\n\n\x08\n\x01\
    \x08\x12\x03\x07\0@\n\t\n\x02\x08\x0b\x12\x03\x07\0@\n\n\n\x02\x04\0\x12\
    \x04\t\0\r\x01\n\n\n\x03\x04\0\x01\x12\x03\t\x08\x10\n\x0b\n\x04\x04\0\
    \x02\0\x12\x03\n\x02\x14\n\r\n\x05\x04\0\x02\0\x04\x12\x04\n\x02\t\x12\n\
    \x0c\n\x05\x04\0\x02\0\x05\x12\x03\n\x02\x07\n\x0c\n\x05\x04\0\x02\0\x01\
    \x12\x03\n\x08\x0f\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\n\x12\x13\n\x0b\n\
    \x04\x04\0\x02\x01\x12\x03\x0b\x02\x11\n\r\n\x05\x04\0\x02\x01\x04\x12\
    \x04\x0b\x02\n\x14\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x0b\x02\x07\n\
    \x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x0b\x08\x0c\n\x0c\n\x05\x04\0\x02\
    \x01\x03\x12\x03\x0b\x0f\x10\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x0c\x02\
    \x13\n\r\n\x05\x04\0\x02\x02\x04\x12\x04\x0c\x02\x0b\x11\n\x0c\n\x05\x04\
    \0\x02\x02\x05\x12\x03\x0c\x02\x07\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\
    \x0c\x08\x0e\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x0c\x11\x12\n\n\n\x02\
    \x04\x01\x12\x04\x0f\0\x14\x01\n\n\n\x03\x04\x01\x01\x12\x03\x0f\x08\x13\
    \n\x0b\n\x04\x04\x01\x02\0\x12\x03\x10\x02\x14\n\r\n\x05\x04\x01\x02\0\
    \x04\x12\x04\x10\x02\x0f\x15\n\x0c\n\x05\x04\x01\x02\0\x06\x12\x03\x10\
    \x02\n\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x10\x0b\x0f\n\x0c\n\x05\x04\
    \x01\x02\0\x03\x12\x03\x10\x12\x13\n\x0b\n\x04\x04\x01\x02\x01\x12\x03\
    \x11\x02\x12\n\r\n\x05\x04\x01\x02\x01\x04\x12\x04\x11\x02\x10\x14\n\x0c\
    \n\x05\x04\x01\x02\x01\x06\x12\x03\x11\x02\n\n\x0c\n\x05\x04\x01\x02\x01\
    \x01\x12\x03\x11\x0b\r\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\x11\x10\
    \x11\n\x0b\n\x04\x04\x01\x02\x02\x12\x03\x12\x02\x14\n\r\n\x05\x04\x01\
    \x02\x02\x04\x12\x04\x12\x02\x11\x12\n\x0c\n\x05\x04\x01\x02\x02\x05\x12\
    \x03\x12\x02\x07\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x03\x12\x08\x0f\n\
    \x0c\n\x05\x04\x01\x02\x02\x03\x12\x03\x12\x12\x13\n\x0b\n\x04\x04\x01\
    \x02\x03\x12\x03\x13\x02\x16\n\r\n\x05\x04\x01\x02\x03\x04\x12\x04\x13\
    \x02\x12\x14\n\x0c\n\x05\x04\x01\x02\x03\x05\x12\x03\x13\x02\x07\n\x0c\n\
    \x05\x04\x01\x02\x03\x01\x12\x03\x13\x08\x11\n\x0c\n\x05\x04\x01\x02\x03\
    \x03\x12\x03\x13\x14\x15\n\n\n\x02\x04\x02\x12\x04\x16\0\x1a\x01\n\n\n\
    \x03\x04\x02\x01\x12\x03\x16\x08\x13\n\x0b\n\x04\x04\x02\x02\0\x12\x03\
    \x17\x02\x14\n\r\n\x05\x04\x02\x02\0\x04\x12\x04\x17\x02\x16\x15\n\x0c\n\
    \x05\x04\x02\x02\0\x06\x12\x03\x17\x02\n\n\x0c\n\x05\x04\x02\x02\0\x01\
    \x12\x03\x17\x0b\x0f\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03\x17\x12\x13\n\
    \x0b\n\x04\x04\x02\x02\x01\x12\x03\x18\x02\x11\n\r\n\x05\x04\x02\x02\x01\
    \x04\x12\x04\x18\x02\x17\x14\n\x0c\n\x05\x04\x02\x02\x01\x05\x12\x03\x18\
    \x02\x07\n\x0c\n\x05\x04\x02\x02\x01\x01\x12\x03\x18\x08\x0c\n\x0c\n\x05\
    \x04\x02\x02\x01\x03\x12\x03\x18\x0f\x10\n\x0b\n\x04\x04\x02\x02\x02\x12\
    \x03\x19\x02\x16\n\r\n\x05\x04\x02\x02\x02\x04\x12\x04\x19\x02\x18\x11\n\
    \x0c\n\x05\x04\x02\x02\x02\x05\x12\x03\x19\x02\x07\n\x0c\n\x05\x04\x02\
    \x02\x02\x01\x12\x03\x19\x08\x11\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\x03\
    \x19\x14\x15\n\n\n\x02\x04\x03\x12\x04\x1c\0\x20\x01\n\n\n\x03\x04\x03\
    \x01\x12\x03\x1c\x08\x16\n\x0b\n\x04\x04\x03\x02\0\x12\x03\x1d\x02\x14\n\
    \r\n\x05\x04\x03\x02\0\x04\x12\x04\x1d\x02\x1c\x18\n\x0c\n\x05\x04\x03\
    \x02\0\x06\x12\x03\x1d\x02\n\n\x0c\n\x05\x04\x03\x02\0\x01\x12\x03\x1d\
    \x0b\x0f\n\x0c\n\x05\x04\x03\x02\0\x03\x12\x03\x1d\x12\x13\n\x0b\n\x04\
    \x04\x03\x02\x01\x12\x03\x1e\x02\x15\n\r\n\x05\x04\x03\x02\x01\x04\x12\
    \x04\x1e\x02\x1d\x14\n\x0c\n\x05\x04\x03\x02\x01\x05\x12\x03\x1e\x02\x07\
    \n\x0c\n\x05\x04\x03\x02\x01\x01\x12\x03\x1e\x08\x10\n\x0c\n\x05\x04\x03\
    \x02\x01\x03\x12\x03\x1e\x13\x14\n\x0b\n\x04\x04\x03\x02\x02\x12\x03\x1f\
    \x02\x16\n\r\n\x05\x04\x03\x02\x02\x04\x12\x04\x1f\x02\x1e\x15\n\x0c\n\
    \x05\x04\x03\x02\x02\x05\x12\x03\x1f\x02\x07\n\x0c\n\x05\x04\x03\x02\x02\
    \x01\x12\x03\x1f\x08\x11\n\x0c\n\x05\x04\x03\x02\x02\x03\x12\x03\x1f\x14\
    \x15\n\n\n\x02\x04\x04\x12\x04\"\0&\x01\n\n\n\x03\x04\x04\x01\x12\x03\"\
    \x08\x12\n\x0b\n\x04\x04\x04\x02\0\x12\x03#\x02\x14\n\r\n\x05\x04\x04\
    \x02\0\x04\x12\x04#\x02\"\x14\n\x0c\n\x05\x04\x04\x02\0\x06\x12\x03#\x02\
    \n\n\x0c\n\x05\x04\x04\x02\0\x01\x12\x03#\x0b\x0f\n\x0c\n\x05\x04\x04\
    \x02\0\x03\x12\x03#\x12\x13\n\x0b\n\x04\x04\x04\x02\x01\x12\x03$\x02#\n\
    \x0c\n\x05\x04\x04\x02\x01\x04\x12\x03$\x02\n\n\x0c\n\x05\x04\x04\x02\
    \x01\x06\x12\x03$\x0b\x13\n\x0c\n\x05\x04\x04\x02\x01\x01\x12\x03$\x14\
    \x1e\n\x0c\n\x05\x04\x04\x02\x01\x03\x12\x03$!\"\n\x0b\n\x04\x04\x04\x02\
    \x02\x12\x03%\x02\x16\n\r\n\x05\x04\x04\x02\x02\x04\x12\x04%\x02$#\n\x0c\
    \n\x05\x04\x04\x02\x02\x05\x12\x03%\x02\x07\n\x0c\n\x05\x04\x04\x02\x02\
    \x01\x12\x03%\x08\x11\n\x0c\n\x05\x04\x04\x02\x02\x03\x12\x03%\x14\x15\n\
    \n\n\x02\x04\x05\x12\x04(\0+\x01\n\n\n\x03\x04\x05\x01\x12\x03(\x08\x15\
    \n\x0b\n\x04\x04\x05\x02\0\x12\x03)\x02\x10\n\r\n\x05\x04\x05\x02\0\x04\
    \x12\x04)\x02(\x17\n\x0c\n\x05\x04\x05\x02\0\x05\x12\x03)\x02\x06\n\x0c\
    \n\x05\x04\x05\x02\0\x01\x12\x03)\x07\x0b\n\x0c\n\x05\x04\x05\x02\0\x03\
    \x12\x03)\x0e\x0f\n\x0b\n\x04\x04\x05\x02\x01\x12\x03*\x02\x15\n\r\n\x05\
    \x04\x05\x02\x01\x04\x12\x04*\x02)\x10\n\x0c\n\x05\x04\x05\x02\x01\x05\
    \x12\x03*\x02\x07\n\x0c\n\x05\x04\x05\x02\x01\x01\x12\x03*\x08\x10\n\x0c\
    \n\x05\x04\x05\x02\x01\x03\x12\x03*\x13\x14b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
