use_frameworks!

target 'TokenCoreX_Example' do
  pod 'TokenCoreX', :path => '../'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Alamofire', '~> 5.0.0-beta.2'
  pod 'SwiftProtobuf', '~> 1.0'

  target 'TokenCoreX_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
