[package]
name = "tcx-bch"
version = "0.1.0"
authors = ["Neal Xu <imxuneal@gmail.com>"]
edition = "2018"

[dependencies]
tcx-crypto = { path = "../crypto" }
tcx-chain = { path = "../chain" }
bch_addr = "0.1.0"
hex-literal = "0.1.4"
bitcoin = "0.18"
secp256k1 = "0.12"
tiny-bip39 = "0.6.0"
bitcoin_hashes = "0.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
uuid = { version = "0.7", features = ["serde", "v4"] }
failure = "0.1.5"
num-bigint = "0.2"
num-traits = "0.2"
num-integer = "0.1"
byteorder = "1.3.2"

[replace]
"secp256k1:0.12.3" = { git = 'https://github.com/rust-bitcoin/rust-secp256k1.git' }
