// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cache_derived_key.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CacheDerivedKeyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface CacheDerivedKeyRoot : GPBRootObject
@end

#pragma mark - VerifyDerivedKeyParam

typedef GPB_ENUM(VerifyDerivedKeyParam_FieldNumber) {
  VerifyDerivedKeyParam_FieldNumber_Id_p = 1,
  VerifyDerivedKeyParam_FieldNumber_DerivedKey = 2,
};

GPB_FINAL @interface VerifyDerivedKeyParam : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *derivedKey;

@end

#pragma mark - DerivedKeyResult

typedef GPB_ENUM(DerivedKeyResult_FieldNumber) {
  DerivedKeyResult_FieldNumber_Id_p = 1,
  DerivedKeyResult_FieldNumber_DerivedKey = 2,
};

GPB_FINAL @interface DerivedKeyResult : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *derivedKey;

@end

#pragma mark - CacheDerivedKeyResult

typedef GPB_ENUM(CacheDerivedKeyResult_FieldNumber) {
  CacheDerivedKeyResult_FieldNumber_Id_p = 1,
  CacheDerivedKeyResult_FieldNumber_EnableDerivedKey = 2,
  CacheDerivedKeyResult_FieldNumber_Mode = 3,
};

GPB_FINAL @interface CacheDerivedKeyResult : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) BOOL enableDerivedKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mode;

@end

#pragma mark - WalletId

typedef GPB_ENUM(WalletId_FieldNumber) {
  WalletId_FieldNumber_Id_p = 1,
};

GPB_FINAL @interface WalletId : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

#pragma mark - BiometricModeResult

typedef GPB_ENUM(BiometricModeResult_FieldNumber) {
  BiometricModeResult_FieldNumber_Mode = 1,
};

GPB_FINAL @interface BiometricModeResult : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *mode;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
